services:
  backend:
    build:
      context: ./simpleapi
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - database

  database:
    build:
      context: ./database
    env_file:
      - .env
    networks:
      - app-network
      - proxy-network

  httpd:
    build:
      context: ./serveur
    ports:
      - "80:80"
    networks:
      - proxy-network
    depends_on:
      - backend

networks:
  app-network:
  proxy-network:

volumes:
  db-data:
