name: CI devops 2025

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Build and test with Maven
        run: mvn -f tp_docker1/simpleapi/pom.xml clean verify

  sonar-cloud:
    runs-on: ubuntu-24.04
    needs: test-backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: SonarCloud Analyze (Maven)
        working-directory: ./tp_docker1/simpleapi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B verify --file ./tp_docker1/simpleapi/pom.xml
          mvn -B sonar:sonar \
            -Dsonar.projectKey=lucie769_dockertptd \
            -Dsonar.organization=lucie769 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            --file ./tp_docker1/simpleapi/pom.xml


  build-and-push-docker-image:
    needs: sonar-cloud
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push backend image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: ./tp_docker1/simpleapi
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-backend:latest

      - name: Build and push database image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: ./tp_docker1/database
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-database:latest

      - name: Build and push httpd image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: ./tp_docker1/serveur
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-httpd:latest
