name: CI devops 2025

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build and test with Maven
        run: mvn -f tp_docker1/simpleapi/pom.xml clean verify

  sonar-cloud:
    runs-on: ubuntu-24.04
    needs: test-backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: SonarCloud Analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -f tp_docker1/simpleapi/pom.xml verify sonar:sonar \
          -Dsonar.projectKey=lucie769_dockertptd \
          -Dsonar.organization=lucie769 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${SONAR_TOKEN}

  build-and-push-docker-image:
    needs: sonar-cloud
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./tp_docker1/simpleapi
          push: true
          tags: luciemoreau/my-backend:latest
      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: ./tp_docker1/database
          push: true
          tags: luciemoreau/my-database:latest
      - name: Build and push httpd image
        uses: docker/build-push-action@v6
        with:
          context: ./tp_docker1/serveur
          push: true
          tags: luciemoreau/my-httpd:latest
